#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."

# 成像方式消融：每个 64 点窗口只生成一张图（gaf / adaptive_heatmap / tivit_grayscale / ordinary_line），
# 不含折线图分支、粒度门控和交叉注意力；视觉与数值特征经 InfoNCE 对齐后做 concat_attn 融合。
# 其余参数取自论文结果对应的运行：Shimmer10 用 batch 4 与窗口级选择（ordinary_line 用 batch 1），
# PADS11 用默认 lr/dropout/对齐权重。
# 所有数据集与 seed 的训练参数均在下方逐条列出，可直接修改对应命令。
# 运行前激活 Python 环境；PYTHON_BIN 可指定解释器，DRY_RUN=1 只打印命令。
# 每个数据集占一张 GPU，各条命令依次运行；数据集之间并行。
METHOD=Ablation_Imaging
source scripts/lib/explicit_experiments.sh

# Subject-Independent
# TDBRAIN Dataset
(
export CUDA_VISIBLE_DEVICES=0

# TDBRAIN — gaf — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/gaf_tdbrain" \
  --result_dir "$RESULT_ROOT/seed42/gaf_tdbrain" \
  "$@"

# TDBRAIN — gaf — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/gaf_tdbrain" \
  --result_dir "$RESULT_ROOT/seed43/gaf_tdbrain" \
  "$@"

# TDBRAIN — gaf — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/gaf_tdbrain" \
  --result_dir "$RESULT_ROOT/seed44/gaf_tdbrain" \
  "$@"

# TDBRAIN — adaptive_heatmap — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/adaptive_heatmap_tdbrain" \
  --result_dir "$RESULT_ROOT/seed42/adaptive_heatmap_tdbrain" \
  "$@"

# TDBRAIN — adaptive_heatmap — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/adaptive_heatmap_tdbrain" \
  --result_dir "$RESULT_ROOT/seed43/adaptive_heatmap_tdbrain" \
  "$@"

# TDBRAIN — adaptive_heatmap — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/adaptive_heatmap_tdbrain" \
  --result_dir "$RESULT_ROOT/seed44/adaptive_heatmap_tdbrain" \
  "$@"

# TDBRAIN — tivit_grayscale — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/tivit_grayscale_tdbrain" \
  --result_dir "$RESULT_ROOT/seed42/tivit_grayscale_tdbrain" \
  "$@"

# TDBRAIN — tivit_grayscale — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/tivit_grayscale_tdbrain" \
  --result_dir "$RESULT_ROOT/seed43/tivit_grayscale_tdbrain" \
  "$@"

# TDBRAIN — tivit_grayscale — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/tivit_grayscale_tdbrain" \
  --result_dir "$RESULT_ROOT/seed44/tivit_grayscale_tdbrain" \
  "$@"

# TDBRAIN — ordinary_line — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/ordinary_line_tdbrain" \
  --result_dir "$RESULT_ROOT/seed42/ordinary_line_tdbrain" \
  "$@"

# TDBRAIN — ordinary_line — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/ordinary_line_tdbrain" \
  --result_dir "$RESULT_ROOT/seed43/ordinary_line_tdbrain" \
  "$@"

# TDBRAIN — ordinary_line — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names TDBRAIN \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/ordinary_line_tdbrain" \
  --result_dir "$RESULT_ROOT/seed44/ordinary_line_tdbrain" \
  "$@"

) &
PIDS+=("$!")

# Subject-Independent
# APAVA Dataset
(
export CUDA_VISIBLE_DEVICES=1

# APAVA — gaf — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/gaf_apava" \
  --result_dir "$RESULT_ROOT/seed42/gaf_apava" \
  "$@"

# APAVA — gaf — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/gaf_apava" \
  --result_dir "$RESULT_ROOT/seed43/gaf_apava" \
  "$@"

# APAVA — gaf — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/gaf_apava" \
  --result_dir "$RESULT_ROOT/seed44/gaf_apava" \
  "$@"

# APAVA — adaptive_heatmap — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/adaptive_heatmap_apava" \
  --result_dir "$RESULT_ROOT/seed42/adaptive_heatmap_apava" \
  "$@"

# APAVA — adaptive_heatmap — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/adaptive_heatmap_apava" \
  --result_dir "$RESULT_ROOT/seed43/adaptive_heatmap_apava" \
  "$@"

# APAVA — adaptive_heatmap — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/adaptive_heatmap_apava" \
  --result_dir "$RESULT_ROOT/seed44/adaptive_heatmap_apava" \
  "$@"

# APAVA — tivit_grayscale — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/tivit_grayscale_apava" \
  --result_dir "$RESULT_ROOT/seed42/tivit_grayscale_apava" \
  "$@"

# APAVA — tivit_grayscale — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/tivit_grayscale_apava" \
  --result_dir "$RESULT_ROOT/seed43/tivit_grayscale_apava" \
  "$@"

# APAVA — tivit_grayscale — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/tivit_grayscale_apava" \
  --result_dir "$RESULT_ROOT/seed44/tivit_grayscale_apava" \
  "$@"

# APAVA — ordinary_line — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/ordinary_line_apava" \
  --result_dir "$RESULT_ROOT/seed42/ordinary_line_apava" \
  "$@"

# APAVA — ordinary_line — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/ordinary_line_apava" \
  --result_dir "$RESULT_ROOT/seed43/ordinary_line_apava" \
  "$@"

# APAVA — ordinary_line — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets eeg \
  --dataset_names APAVA \
  --data_dir "$NEUROSIGVIA_EEG_ROOT" \
  --eeg_protocol medformer_code_exact \
  --eeg_normalization per_window_per_channel_standard_scaler_ddof0 \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 8 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/ordinary_line_apava" \
  --result_dir "$RESULT_ROOT/seed44/ordinary_line_apava" \
  "$@"

) &
PIDS+=("$!")

# Subject-Independent
# Shimmer10 Dataset
(
export CUDA_VISIBLE_DEVICES=2

# Shimmer10 — gaf — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/gaf_shimmer10" \
  --result_dir "$RESULT_ROOT/seed42/gaf_shimmer10" \
  "$@"

# Shimmer10 — gaf — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/gaf_shimmer10" \
  --result_dir "$RESULT_ROOT/seed43/gaf_shimmer10" \
  "$@"

# Shimmer10 — gaf — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/gaf_shimmer10" \
  --result_dir "$RESULT_ROOT/seed44/gaf_shimmer10" \
  "$@"

# Shimmer10 — adaptive_heatmap — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/adaptive_heatmap_shimmer10" \
  --result_dir "$RESULT_ROOT/seed42/adaptive_heatmap_shimmer10" \
  "$@"

# Shimmer10 — adaptive_heatmap — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/adaptive_heatmap_shimmer10" \
  --result_dir "$RESULT_ROOT/seed43/adaptive_heatmap_shimmer10" \
  "$@"

# Shimmer10 — adaptive_heatmap — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/adaptive_heatmap_shimmer10" \
  --result_dir "$RESULT_ROOT/seed44/adaptive_heatmap_shimmer10" \
  "$@"

# Shimmer10 — tivit_grayscale — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/tivit_grayscale_shimmer10" \
  --result_dir "$RESULT_ROOT/seed42/tivit_grayscale_shimmer10" \
  "$@"

# Shimmer10 — tivit_grayscale — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/tivit_grayscale_shimmer10" \
  --result_dir "$RESULT_ROOT/seed43/tivit_grayscale_shimmer10" \
  "$@"

# Shimmer10 — tivit_grayscale — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 4 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/tivit_grayscale_shimmer10" \
  --result_dir "$RESULT_ROOT/seed44/tivit_grayscale_shimmer10" \
  "$@"

# Shimmer10 — ordinary_line — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 1 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/ordinary_line_shimmer10" \
  --result_dir "$RESULT_ROOT/seed42/ordinary_line_shimmer10" \
  "$@"

# Shimmer10 — ordinary_line — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 1 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/ordinary_line_shimmer10" \
  --result_dir "$RESULT_ROOT/seed43/ordinary_line_shimmer10" \
  "$@"

# Shimmer10 — ordinary_line — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names Shimmer_10_session10_AFC \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode shimmer_hc_vs_pd \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 1 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/ordinary_line_shimmer10" \
  --result_dir "$RESULT_ROOT/seed44/ordinary_line_shimmer10" \
  "$@"

) &
PIDS+=("$!")

# Subject-Independent
# PADS11 Dataset
(
export CUDA_VISIBLE_DEVICES=3

# PADS11 — gaf — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/gaf_pads11" \
  --result_dir "$RESULT_ROOT/seed42/gaf_pads11" \
  "$@"

# PADS11 — gaf — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/gaf_pads11" \
  --result_dir "$RESULT_ROOT/seed43/gaf_pads11" \
  "$@"

# PADS11 — gaf — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation gaf \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/gaf_pads11" \
  --result_dir "$RESULT_ROOT/seed44/gaf_pads11" \
  "$@"

# PADS11 — adaptive_heatmap — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/adaptive_heatmap_pads11" \
  --result_dir "$RESULT_ROOT/seed42/adaptive_heatmap_pads11" \
  "$@"

# PADS11 — adaptive_heatmap — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/adaptive_heatmap_pads11" \
  --result_dir "$RESULT_ROOT/seed43/adaptive_heatmap_pads11" \
  "$@"

# PADS11 — adaptive_heatmap — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation adaptive_heatmap \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/adaptive_heatmap_pads11" \
  --result_dir "$RESULT_ROOT/seed44/adaptive_heatmap_pads11" \
  "$@"

# PADS11 — tivit_grayscale — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/tivit_grayscale_pads11" \
  --result_dir "$RESULT_ROOT/seed42/tivit_grayscale_pads11" \
  "$@"

# PADS11 — tivit_grayscale — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/tivit_grayscale_pads11" \
  --result_dir "$RESULT_ROOT/seed43/tivit_grayscale_pads11" \
  "$@"

# PADS11 — tivit_grayscale — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation tivit_grayscale \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/tivit_grayscale_pads11" \
  --result_dir "$RESULT_ROOT/seed44/tivit_grayscale_pads11" \
  "$@"

# PADS11 — ordinary_line — seed 42
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 42 \
  --feature_cache_dir "$CACHE_ROOT/seed42/ordinary_line_pads11" \
  --result_dir "$RESULT_ROOT/seed42/ordinary_line_pads11" \
  "$@"

# PADS11 — ordinary_line — seed 43
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 43 \
  --feature_cache_dir "$CACHE_ROOT/seed43/ordinary_line_pads11" \
  --result_dir "$RESULT_ROOT/seed43/ordinary_line_pads11" \
  "$@"

# PADS11 — ordinary_line — seed 44
python \
  -u \
  -m runners.neurosigvia \
  --datasets wearable \
  --dataset_names PADS_11_task08_TouchIndex \
  --data_dir "$NEUROSIGVIA_WEARABLE_ROOT" \
  --wearable_label_mode pads_pd_vs_hc \
  --vit_1_name "${MODEL_DIR:-${NEUROSIGVIA_CLIP_PATH:-../models/CLIP-ViT-H-14-laion2B-s32B-b79K}}" \
  --vit_1_layer 14 \
  --aggregation mean \
  --image_mode multiscale_activity_graph \
  --activity_graph_granularity_hidden_dim 64 \
  --mantis \
  --mantis_name "${MANTIS_DIR:-${NEUROSIGVIA_MANTIS_PATH:-../models/Mantis-8M}}" \
  --classifier_type mlp \
  --modal_interaction adaptive_granularity \
  --outer_patch_size 64 \
  --outer_patch_stride 64 \
  --granularity_gate_temperature 0.5 \
  --granularity_balance_weight 0 \
  --granularity_graph_token_grid 4 \
  --activity_graph_canvas_size 360 \
  --activity_graph_line_width 1.0 \
  --activity_graph_vertical_margin 0.05 \
  --patch_alignment_dim 256 \
  --patch_alignment_temperature 0.1 \
  --patch_alignment_weight 0.1 \
  --patch_checkpoint_metric window_macro_f1 \
  --visual_encode_batch_size 4 \
  --fusion_dim 128 \
  --fusion_heads 2 \
  --mlp_hidden_dim 128 \
  --mlp_num_layers 2 \
  --mlp_dropout 0.1 \
  --mlp_lr 3e-4 \
  --mlp_weight_decay 1e-3 \
  --mlp_class_weight balanced \
  --mlp_epochs 100 \
  --mlp_early_stop_strategy raw_primary \
  --mlp_early_stop_warmup_epochs 10 \
  --mlp_early_stop_min_epochs 0 \
  --mlp_early_stop_patience 12 \
  --mlp_early_stop_min_delta 0.002 \
  --mlp_lr_scheduler reduce_on_plateau \
  --mlp_lr_scheduler_patience 4 \
  --mlp_lr_scheduler_factor 0.5 \
  --mlp_lr_scheduler_min_lr 1e-6 \
  --batch_size 16 \
  --image_representation ordinary_line \
  --heatmap_patch_size 8 \
  --pretrain_epochs 0 \
  --random_seed 44 \
  --feature_cache_dir "$CACHE_ROOT/seed44/ordinary_line_pads11" \
  --result_dir "$RESULT_ROOT/seed44/ordinary_line_pads11" \
  "$@"

) &
PIDS+=("$!")

wait_for_jobs "${PIDS[@]}"
